version: '3.8'

services:
  database:
    image: database
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"


  brt-microservice:
    image: brt-microservice
    ports:
      - "8082:8080"
    depends_on:
      database:
        condition: service_healthy
      hrs-microservice:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/BRT
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=update
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8083
      - cdr.microservice.address=http://cdr-microservice:8081
      - brt.microservice.address=http://brt-microservice:8082

  hrs-microservice:
    image: hrs-microservice
    ports:
      - "8083:8080"
    environment:
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8083
      - cdr.microservice.address=http://cdr-microservice:8081
      - brt.microservice.address=http://brt-microservice:8082

  cdr-microservice:
    image: cdr-microservice
    ports:
      - "8081:8080"
    depends_on:
      brt-microservice:
        condition: service_started
    environment:
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8083
      - cdr.microservice.address=http://cdr-microservice:8081
      - brt.microservice.address=http://brt-microservice:8082

  srm-microservice:
    image: srm-microservice
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      brt-microservice:
        condition: service_started
      cdr-microservice:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/SRM-Users
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=update
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8083
      - cdr.microservice.address=http://cdr-microservice:8081
      - brt.microservice.address=http://brt-microservice:8082