version: '3.8'

services:
  database:
    image: alkafol/tarification-system:database
    restart: always
    healthcheck:
      test: [ "CMD", "pg_isready","-d","postgres","-U","postgres" ]
      interval: 5s
      timeout: 1s
      retries: 5
      start_period: 5s
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  rabbitMQ:
    image: rabbitmq:3.10.7-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: 1234
    ports:
      - "5672:5672"
      - "15672:15672"

  brt-microservice:
    image: alkafol/tarification-system:brt-microservice
    healthcheck:
      test: "./wait-for-it.sh localhost:8080"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8082:8080"
    depends_on:
      database:
        condition: service_healthy
      hrs-microservice:
        condition: service_healthy
      rabbitMQ:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/BRT
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=update
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8080
      - cdr.microservice.address=http://cdr-microservice:8080
      - brt.microservice.address=http://brt-microservice:8080
      - server.port=8080
      - spring.rabbitmq.host=rabbitMQ
      - spring.rabbitmq.username=admin
      - spring.rabbitmq.password=1234

  hrs-microservice:
    image: alkafol/tarification-system:hrs-microservice
    healthcheck:
      test: "./wait-for-it.sh localhost:8080"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "8083:8080"
    environment:
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8080
      - cdr.microservice.address=http://cdr-microservice:8080
      - brt.microservice.address=http://brt-microservice:8080
      - server.port=8080

  cdr-microservice:
    image: alkafol/tarification-system:cdr-microservice
    ports:
      - "8081:8080"
    depends_on:
      brt-microservice:
        condition: service_healthy
    environment:
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8080
      - cdr.microservice.address=http://cdr-microservice:8080
      - brt.microservice.address=http://brt-microservice:8080
      - server.port=8080

  srm-microservice:
    image: alkafol/tarification-system:srm-microservice
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
      brt-microservice:
        condition: service_healthy
      cdr-microservice:
        condition: service_started
      rabbitMQ:
        condition: service_started
    environment:
      - spring.datasource.url=jdbc:postgresql://database:5432/SRM-Users
      - spring.datasource.username=postgres
      - spring.datasource.password=1234
      - spring.jpa.hibernate.ddl-auto=update
      - srm.microservice.address=http://srm-microservice:8080
      - hrs.microservice.address=http://hrs-microservice:8080
      - cdr.microservice.address=http://cdr-microservice:8080
      - brt.microservice.address=http://brt-microservice:8080
      - server.port=8080
      - spring.rabbitmq.host=rabbitMQ
      - spring.rabbitmq.username=admin
      - spring.rabbitmq.password=1234